# Generated by Django 4.2.6 on 2023-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Номер заказа'),
        ),
    ]
